app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');
Route::get('empleado', 'EmpleadoController@index');
Route::get('empleadoorm', 'EmpleadoController@indexOrm');


Route::group([ 'prefix' => 'admin', 'namespace' => 'Admin' ], function () {
	Route::resource('users','UsersController');	 	
	Route::resource('puestos','PuestosController');
	Route::resource('roles','RolesController');
	Route::resource('areas','AreasController');
	Route::resource('estatus','EstatusController');
});

Route::group([ 'prefix' => 'fnz', 'namespace' => 'Finanzas' ], function () {
	Route::resource('proy','ProyectosController');	 	
});

Route::group([ 'prefix' => 'bpo', 'namespace' => 'BPO' ], function () {
	Route::resource('proyectos','BposController');	 	
});
Route::controllers([
	'auth' => 'Auth\AuthController',	
	'password' => 'Auth\PasswordController'
//	,'empleado' => 'EmpleadoController'
]);

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>MásNegocio - Interno</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  	
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar">JAv</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">HomeBlack</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/') }}">Inicio</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Registro</a></li>
						
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Cerrar</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<script>
  $(function() {
    $( "#fecha_ing" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
     $( "#fecha_inicio" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
     $( "#fecha_final" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
    $( "#fecha_baja" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
    $( "#fecha_cambio" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
    //DATAPICKER BPO
    $( "#FECHACOMPRA" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
    $( "#FECHAINI" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
    $( "#FECHAFIN" ).datepicker({
      showOtherMonths: true,
      selectOtherMonths: true
    });
  });
  </script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">
					Inicio
				</div>

				<div class="panel-body" align="center">
					
					
					@if( Auth::user()->clave_area === "100" )
					<table aling="center">
						<tr>
							@if( Auth::user()->clave_rol === "1000" )
								<td>Empleado </td>
								<td>Catalogo de Roles</td>
								<td>Catalogo de Areas</td>
							@endif

						</tr>
						<tr>

							
							@if( Auth::user()->clave_rol === "1000" )
								<td><a href= "{{ url('/admin/users') }}" >{!! Html::image('img/user.png', 'a picture'
									, array('class' => 'img-circle', 'width'=>'140px', 'title' => 'Empleado')) !!}</td>
								<td><a href= "{{ route('admin.roles.index') }}" >{!! Html::image('img/rol.png', 'Catalogo de Roles', array('class' => 'img-circle')) !!}}</a></td>
								<td><a href= "{{ route('admin.areas.index') }}" >{!! Html::image('img/area.png', 'Catalogo de Areas', array('class' => 'img-circle', 'width'=>'150px')) !!} </a></td>
							@endif
							
							@if( Auth::user()->clave_rol === "1001" )
								<td><a href= "{{ route('fnz.proy.index') }}" >{!! Html::image('img/mnu_fiananzas.jpg', 'Finanzas', array('class' => 'img-circle','width'=>'250px')) !!}</a></td>	
							@endif
							
							@if( Auth::user()->clave_rol === "1002" )
								<td><a href= "{{ route('bpo.proyectos.index') }}" >{!! Html::image('img/mnu_bpo-1.png', 'Finanzas', array('class' => 'img-circle','width'=>'250px')) !!}</a></td>	
							@endif
						</tr>
						@if( Auth::user()->clave_rol === "1000" )
						<tr>
							<td><p></p></td>
						</tr>
						<tr>
							<td>Catalogo de puestos</td>
							<td>Catalogo de estatus</td>

						</tr>
						<tr>
							<td><a href= "{{ route('admin.puestos.index') }}" >{!! Html::image('img/puesto.png', 'Catalogo de Puesto', array('class' => 'img-circle', 'width'=>'150px')) !!} </a></td>
							<td><a href= "{{ route('admin.estatus.index') }}" >{!! Html::image('img/activoInactivo.png', 'Catalogo de estatus', array('class' => 'img-circle', 'width'=>'150px')) !!} </a></td>
						</tr>
						@endif
					</table>
				</div>
				@endif
				@if( Auth::user()->clave_area != "100" )
				<div class="alert alert-danger" role="alert">
					<p>
						<h1>Area Restringida</h1>
					</p>
				</div>
				@endif
			</div>
		</div>
	</div>
</div>
@endsection