app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');
Route::get('empleado', 'EmpleadoController@index');
Route::get('empleadoorm', 'EmpleadoController@indexOrm');


Route::group([ 'prefix' => 'admin', 'namespace' => 'Admin' ], function () {
	Route::resource('users','UsersController');	 	
	Route::resource('puestos','PuestosController');
	Route::resource('roles','RolesController');
	Route::resource('areas','AreasController');
	Route::resource('estatus','EstatusController');
});

Route::group([ 'prefix' => 'fnz', 'namespace' => 'Finanzas' ], function () {
	Route::resource('proy','ProyectosController');	 	
});

Route::group([ 'prefix' => 'bpo', 'namespace' => 'BPO' ], function () {
	Route::resource('proyectos','BposController');	 	
});
Route::controllers([
	'auth' => 'Auth\AuthController',	
	'password' => 'Auth\PasswordController'
//	,'empleado' => 'EmpleadoController'
]);

app/Http/Controllers/Admin/PuestoController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;
use Illuminate\Http\Request;

class PuestosController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$users = "";User::paginate();
		//dd ($users);
		return view('admin.users.catPuesto', compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		
		return view('admin.users.crear', compact('users'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/Http/Controllers/Admin/PuestosController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CrearPuestoRequest;

use Illuminate\Http\Request;
use Illuminate\Http\Redirect;
use Log;
use App\Model\Puesto;

class PuestosController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		$puestos = Puesto::descripcion($request->get('desc'))
								->clave($request->get('clave'))
								->paginate();
		return view('admin.puestos.index', compact('puestos'));
		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		
		return view('admin.puestos.crear');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CrearPuestoRequest $request)
	{
		Log::info('Puesto store');
		//dd($request->all());
		$puesto = new Puesto($request->all());
		$puesto->save();
		Log::info('Puesto store save');
		$clave = $request->get('clave_puesto');
		$notices = array("Registro creado, clave : $clave");
		$puestos = Puesto::paginate();
		return view('admin.puestos.index', compact('puestos', 'notices'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		Log::info('Puesto editar id: '.$id);
		$puesto = Puesto::findOrFail($id);
		return view('admin.puestos.editar', compact('puesto'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id,CrearPuestoRequest $request)
	{
		Log::info('Puesto actualizar id: '.$id);
		//	Log::info(print_r(Request::all(),true));
		$puesto = Puesto::findOrFail($id);
		Log::info(print_r($request->all(),TRUE));
		$puesto->fill($request->all());
		Log::info("Fill  exito");
		$puesto->save();
		Log::info("Save exito");
		$puestos = Puesto::paginate();
		$notices = array("Actualizacion Exitosa");
		return view('admin.puestos.index', compact('puestos', 'notices'));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$puesto = Puesto::find($id);
		$puesto->delete();
		$puestos = Puesto::paginate();
		$notices = array("Registro Eliminado");
		return view('admin.puestos.index', compact('puestos', 'notices'));
	}

}

resources/views/admin/puestos/crear.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Crear Puesto</div>

				<div class="panel-body">
					@include('errors.parcial.campos_error')
					{!! Form::open([ 'route' => 'admin.puestos.store', 'method' => 'POST' ]) !!}
						  	@include('admin.puestos.parcial.campos')					  
						<button type="submit" class="btn btn-info" >Guardar </button>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/puestos/editar.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Actualizar Puesto {{ $puesto-> clave_puesto}}</div>

				<div class="panel-body">
					@include('errors.parcial.campos_error')
					{!! Form::model($puesto, [ 'route' => ['admin.puestos.update',$puesto], 'method' => 'PUT' ]) !!}
						  	@include('admin.puestos.parcial.campos')					  
						<button type="submit" class="btn btn-info" >Guardar </button>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/puestos/index.blade.php
	@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Puestos</div>

				<div class="panel-body">
					@if( isset($notices))
					<p>
						<div class="alert alert-warning" role="alert">
							@foreach($notices as $notice)
							<p></p>
							<strong> {{ $notice }} </strong>
							@endforeach
						</div>
					</p>
					@endif
					{!! Form::model(Request::only(['desc','clave']), [ 'route' => ['admin.puestos.index'], 'method' => 'GET', 'class'=>'navbar-form navbar-left pull-right', 'role'=>'search' ]) !!}				
						<div class="form-group">
							{!! Form::text( 'desc', null, ['class' => 'form-control', 'placeholder' => 'Descripcion' ]) !!}
							{!! Form::text( 'clave', null, ['class' => 'form-control', 'placeholder' => 'Clave' ]) !!}
						</div>
						<button type="submit" class="btn btn-default">
							Buscar
						</button>
					
					{!! Form::close() !!}
					<p>
						<a class="btn btn-success" href=" {{ route('admin.puestos.create') }} " role="button">
							Nuevo Puesto
						</a>
					</p>
					Usuarios registrados {{ $puestos ->total()}}, Total de paginas {{ $puestos ->lastPage()}} , Pagina actual {{ $puestos ->currentPage()}}  
					{!! $puestos->appends(Request::only(['desc','clave']))->render() !!} 
					</p>
					<table class="table table-striped"> 
						<tr>
							<th>Clave del puesto</th>
							<th>Descripción del puesto</th>
							<th>Acciones</th>
						</tr>
						@foreach($puestos as $puesto)
						<tr>
							<th>{{ $puesto -> clave_puesto}}</th>
							<th>{{ $puesto -> desc_puesto}}</th>
							
							<th>
								{!! Form::open([ 'route' => ['admin.puestos.destroy', $puesto], 'method' => 'DELETE' ]) !!}					  
									<button type="submit" class="btn btn-danger" >Eliminar </button> 
									<a href="{{ route('admin.puestos.edit', $puesto->id) }}" class="btn btn-info" >Editar</a>
								{!! Form::close() !!}
								
								
							</th>
						</tr>
						@endforeach
					</table>
					{!! $puestos->appends(Request::only(['desc','clave']))->render() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection