app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');
Route::get('empleado', 'EmpleadoController@index');
Route::get('empleadoorm', 'EmpleadoController@indexOrm');


Route::group([ 'prefix' => 'admin', 'namespace' => 'Admin' ], function () {
	Route::resource('users','UsersController');	 	
	Route::resource('puestos','PuestosController');
	Route::resource('roles','RolesController');
	Route::resource('areas','AreasController');
	Route::resource('estatus','EstatusController');
});

Route::group([ 'prefix' => 'fnz', 'namespace' => 'Finanzas' ], function () {
	Route::resource('proy','ProyectosController');	 	
});

Route::group([ 'prefix' => 'bpo', 'namespace' => 'BPO' ], function () {
	Route::resource('proyectos','BposController');	 	
});
Route::controllers([
	'auth' => 'Auth\AuthController',	
	'password' => 'Auth\PasswordController'
//	,'empleado' => 'EmpleadoController'
]);

app/Http/Controllers/Admin/AreasController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CrearAreaRequest;

use Log;
use Illuminate\Http\Request;
use Illuminate\Http\Redirect;
use App\Model\Area;

class AreasController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		$areas = Area::descripcion($request->get('desc'))
								->clave($request->get('clave'))
								->paginate();
		return view('admin.areas.index', compact('areas'));
		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('admin.areas.crear');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CrearAreaRequest $request)
	{
		Log::info('Areas store');
		$area = new Area($request->all());
		$area->save();
		Log::info('Area store save');
		$clave = $request->get('clave_area');
		$notices = array("Registro creado, clave : $clave");
		$areas = Area::paginate();
		return view('admin.areas.index', compact('areas', 'notices'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		Log::info('Area editar id: '.$id);
		$area = Area::findOrFail($id);
		return view('admin.areas.editar', compact('area'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, CrearAreaRequest $request)
	{
		Log::info('Area actualizar id: '.$id);
		$area = Area::findOrFail($id);
		Log::info(print_r($request->all(),TRUE));
		$area->fill($request->all());
		Log::info("Fill  exito");
		$area->save();
		Log::info("Save exito");
		$areas = Area::paginate();
		$notices = array("Actualizacion Exitosa");
		return view('admin.areas.index', compact('areas', 'notices'));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$area = Area::find($id);
		$area->delete();
		$areas = Area::paginate();
		$notices = array("Registro Eliminado");
		return view('admin.areas.index', compact('areas','notices'));
	}

}

resources/views/admin/areas/crear.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Crear Areas</div>

				<div class="panel-body">
					@include('errors.parcial.campos_error')
					
					{!! Form::open([ 'route' => 'admin.areas.store', 'method' => 'POST' ]) !!}
						  	@include('admin.areas.parcial.campos')					  
						<button type="submit" class="btn btn-info" >Guardar </button>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/areas/editar.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Actualizar area {{ $area-> clave_area}}</div>

				<div class="panel-body">
					@include('errors.parcial.campos_error')
					{!! Form::model($area, [ 'route' => ['admin.areas.update',$area], 'method' => 'PUT' ]) !!}
						  	@include('admin.areas.parcial.campos')					  
						<button type="submit" class="btn btn-info" >Guardar </button>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/areas/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Areas</div>

				<div class="panel-body">
					@if( isset($notices))
					<p>
						<div class="alert alert-warning" role="alert">
							@foreach($notices as $notice)
							<p></p>
							<strong> {{ $notice }} </strong>
							@endforeach
						</div>
					</p>
					@endif
					{!! Form::model(Request::only(['desc','clave']), [ 'route' => ['admin.areas.index'], 'method' => 'GET', 'class'=>'navbar-form navbar-left pull-right', 'role'=>'search' ]) !!}				
						<div class="form-group">
							{!! Form::text( 'desc', null, ['class' => 'form-control', 'placeholder' => 'Descripcion' ]) !!}
							{!! Form::text( 'clave', null, ['class' => 'form-control', 'placeholder' => 'Clave' ]) !!}
						</div>
						<button type="submit" class="btn btn-default">
							Buscar
						</button>
					
					{!! Form::close() !!}
					<p>
						<a class="btn btn-success" href=" {{ route('admin.areas.create') }} " role="button">
							Nueva Area
						</a>
					</p>
										
					Areas registrados {{ $areas ->total()}}, Total de paginas {{ $areas ->lastPage()}} , Pagina actual {{ $areas ->currentPage()}}  
					{!! $areas->appends(Request::only(['desc','clave']))->render() !!} 
					</p>
					<table class="table table-striped"> 
						<tr>
							<th>Clave del Area</th>
							<th>Descripción del Area</th>
							<th>Acciones</th>
						</tr>
						@foreach($areas as $area)
						<tr>
							<th>{{ $area -> clave_area}}</th>
							<th>{{ $area -> desc_area}}</th>
							
							<th>
								{!! Form::open([ 'route' => ['admin.areas.destroy', $area], 'method' => 'DELETE' ]) !!}					  
									<button type="submit" class="btn btn-danger" >Eliminar </button> 
									<a href="{{ route('admin.areas.edit', $area->id) }}" class="btn btn-info" >Editar</a>
								{!! Form::close() !!}
								
								
							</th>
						</tr>
						@endforeach
					</table>
					{!! $areas->render() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection