app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');
Route::get('empleado', 'EmpleadoController@index');
Route::get('empleadoorm', 'EmpleadoController@indexOrm');


Route::group([ 'prefix' => 'admin', 'namespace' => 'Admin' ], function () {
	Route::resource('users','UsersController');	 	
	Route::resource('puestos','PuestosController');
	Route::resource('roles','RolesController');
	Route::resource('areas','AreasController');
	Route::resource('estatus','EstatusController');
});

Route::group([ 'prefix' => 'fnz', 'namespace' => 'Finanzas' ], function () {
	Route::resource('proy','ProyectosController');	 	
});

Route::group([ 'prefix' => 'bpo', 'namespace' => 'BPO' ], function () {
	Route::resource('proyectos','BposController');	 	
});
Route::controllers([
	'auth' => 'Auth\AuthController',	
	'password' => 'Auth\PasswordController'
//	,'empleado' => 'EmpleadoController'
]);

app/Http/Controllers/Finanzas/ProyectosController.php
<?php namespace App\Http\Controllers\Finanzas;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Redirect;
use Illuminate\Database\Eloquent\Collection;
use Log;

use App\Http\Requests\CrearProyectoRequest;
use App\Model\Finanzas;

class ProyectosController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		//$this->middleware('auth');
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		/*
		$users = User::nombre($request->get('name'))
							->email($request->get('email'))
							->paginate();
		
		
		*/
		$proyectos = Finanzas::paginate();
		
		return view('finanzas.index', compact('proyectos'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		/*$roles 	= array_merge(array("" => "Seleccionar"),Rol::lists('desc_rol','clave_rol'));
		$areas 	= array_merge(array("" => "Seleccionar"),Area::lists('desc_area','clave_area'));
		$puestos= array_merge(array("" => "Seleccionar"),Puesto::lists('desc_puesto','clave_puesto'));
*/
		return view('finanzas.crear');//, compact('roles','areas','puestos'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CrearProyectoRequest $request)
	{
		Log::info('Proyecto store');
		$proyecto = new Finanzas();
		
		$proyecto -> plataforma = $request->get('plataforma');
		$proyecto -> ingresos 	= $request->get('ingresos');
		$proyecto -> fecha_ing 	= \Carbon\Carbon::parse($request->get('fecha_ing'));
		$proyecto -> grossmar	= $request->get('grossmar');
		$proyecto -> ebitda		= $request->get('ebitda');
		$proyecto -> grossideal	= $request->get('grossideal');
		$proyecto -> ebitdaideal= $request->get('ebitdaideal');
		
		$proyecto -> save();
	
		$proyectos = Finanzas::paginate();
		$notices = array('Proyecto creado', "Nomina Agregada");
		return view('finanzas.index', compact('notices', 'proyectos'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		Log::info('Proyecto editar id: '.$id);
		$proyecto = Finanzas::findOrFail($id);
		//dd();
		/*$roles = Rol::lists('desc_rol',"clave_rol");
		$areas 	= Area::lists('desc_area','clave_area');
		$puestos= Puesto::lists('desc_puesto','clave_puesto');
		 */
		return view('finanzas.editar', compact('proyecto'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, CrearProyectoRequest $request)
	{
		Log::info('Proyecto actualizar id: '.$id);
		$finanzas = Finanzas::findOrFail($id);
		Log::info(print_r($request->all(),TRUE));
		$finanzas->fill($request->all());
		Log::info("Fill  exito");
		$finanzas->save();
		Log::info("Save exito");
		$proyectos = Finanzas::paginate();
		return view('finanzas.index', compact('proyectos'))->with('notices',array("Proyecto Actualizado"));
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$proyecto = Finanzas::find($id);
		$proyecto->delete();
		$proyectos = Finanzas::paginate();
		return view('finanzas.index', compact('proyectos'))->with('notices',array("Proyecto eliminado"));
	}

}

resources/views/finanzas/crear.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Nuevo Proyecto</div>

				<div class="panel-body">
					@include('errors.parcial.campos_error')
					{!! Form::open([ 'route' => 'fnz.proy.store', 'method' => 'POST' ]) !!}
						@include('finanzas.parcial.campos')
						  <button type="submit" class="btn btn-info" >Guardar </button>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/finanzas/editar.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Actualizar Usuario {{ $proyecto -> name}}</div>

				<div class="panel-body">
					@include('errors.parcial.campos_error')
					{!! Form::model($proyecto, [ 'route' => ['fnz.proy.update',$proyecto], 'method' => 'PUT' ]) !!}
						  	@include('finanzas.parcial.campos')					  
						<button type="submit" class="btn btn-info" >Guardar </button>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/finanzas/index.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">
					FINANZAS
				</div>
				<div class="panel-body">

					@if( isset($notices) && !empty($notices))
					<p>
						<div class="alert alert-warning" role="alert">
							@foreach($notices as $notice)
							<p></p>
							<strong> {{ $notice }} </strong>
							@endforeach
						</div>
					</p>
					@endif

					{!! Form::model(Request::only(['name','email']), [ 'route' => ['fnz.proy.index'], 'method' => 'GET', 'class'=>'navbar-form navbar-left pull-right', 'role'=>'search' ]) !!}
					<div class="form-group">
						{!! Form::text( 'name', null, ['class' => 'form-control', 'placeholder' => 'Definir campos para busquedar' ]) !!}
					</div>
					<button type="submit" class="btn btn-default" disabled="disabled">
						Buscar
					</button>

					{!! Form::close() !!}
					<p>
						<a class="btn btn-info" href=" {{ route('fnz.proy.create') }} " role="button"> Nuevo  </a>
					</p>
				
					</p>
					<table class="table table-striped">
						<tr>
							<th>ID</th>
							<th>FECHA</th>
							<th>PLATAFORMA</th>
							<th>GROSSMAR</th>
							<th>EBITDA</th>
							<th>GROSSIDEAL</th>
							<th>EBITDAIDEAL</th>
							<th>INGRESOS</th>
						</tr>
						@forelse($proyectos as $proyecto)
							<tr>
								<th>{{ $proyecto -> id}}</th>
								<th>{{ $proyecto -> fecha_ing}}</th>
								<th>{{ $proyecto -> plataforma}}</th>
								<th>{{ $proyecto -> grossmar}}</th>
								<th>{{ $proyecto -> ebitda}}</th>
								<th>{{ $proyecto -> grossideal}}</th>
								<th>{{ $proyecto -> ebitdaideal}}</th>
								<th>{{ $proyecto -> ingresos}}</th>
								<th> {!! Form::open([ 'route' => ['fnz.proy.destroy', $proyecto], 'method' => 'DELETE' ]) !!}
								<button type="submit" class="btn btn-danger" >
									Eliminar
								</button><a href="{{ route('fnz.proy.edit', $proyecto -> id) }}" class="btn btn-info" >Editar</a> {!! Form::close() !!} </th>
							</tr>
						@empty
						    <p>No Proyectos</p>
						@endforelse
					</table>
					
				</div>
			</div>
		</div>
	</div>
</div>
@endsection